// Code generated by protoc-gen-go. DO NOT EDIT.
// source: srv/usermgr/user.proto

package eci_v1_server_user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserRequest struct {
	ID                   int32    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserRequest) Reset()         { *m = UserRequest{} }
func (m *UserRequest) String() string { return proto.CompactTextString(m) }
func (*UserRequest) ProtoMessage()    {}
func (*UserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_04c41526bd5d624e, []int{0}
}

func (m *UserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserRequest.Unmarshal(m, b)
}
func (m *UserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserRequest.Marshal(b, m, deterministic)
}
func (m *UserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserRequest.Merge(m, src)
}
func (m *UserRequest) XXX_Size() int {
	return xxx_messageInfo_UserRequest.Size(m)
}
func (m *UserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserRequest proto.InternalMessageInfo

func (m *UserRequest) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

type UserResponse struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Age                  int32    `protobuf:"varint,2,opt,name=age,proto3" json:"age,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserResponse) Reset()         { *m = UserResponse{} }
func (m *UserResponse) String() string { return proto.CompactTextString(m) }
func (*UserResponse) ProtoMessage()    {}
func (*UserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_04c41526bd5d624e, []int{1}
}

func (m *UserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserResponse.Unmarshal(m, b)
}
func (m *UserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserResponse.Marshal(b, m, deterministic)
}
func (m *UserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserResponse.Merge(m, src)
}
func (m *UserResponse) XXX_Size() int {
	return xxx_messageInfo_UserResponse.Size(m)
}
func (m *UserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserResponse proto.InternalMessageInfo

func (m *UserResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UserResponse) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func init() {
	proto.RegisterType((*UserRequest)(nil), "eci.v1.server.user.UserRequest")
	proto.RegisterType((*UserResponse)(nil), "eci.v1.server.user.UserResponse")
}

func init() { proto.RegisterFile("srv/usermgr/user.proto", fileDescriptor_04c41526bd5d624e) }

var fileDescriptor_04c41526bd5d624e = []byte{
	// 215 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x50, 0xcb, 0x4a, 0xc4, 0x40,
	0x10, 0x64, 0xe2, 0x03, 0x6c, 0x45, 0xa4, 0x0f, 0x1a, 0x04, 0x35, 0xe4, 0x94, 0xd3, 0x18, 0x1f,
	0x5f, 0x20, 0x01, 0xc9, 0x35, 0xc1, 0xab, 0x30, 0xc6, 0x36, 0x0c, 0x98, 0x99, 0x6c, 0xcf, 0x64,
	0x3e, 0x75, 0xbf, 0x67, 0xc9, 0xe4, 0x12, 0x58, 0xf6, 0xb6, 0xa7, 0x2e, 0xba, 0xaa, 0xab, 0x8a,
	0x86, 0x5b, 0xc7, 0xe1, 0x79, 0x72, 0xc4, 0x43, 0xcf, 0x71, 0xca, 0x91, 0xad, 0xb7, 0x88, 0xd4,
	0x69, 0x19, 0x5e, 0xa4, 0x23, 0x0e, 0xc4, 0x72, 0x66, 0xf2, 0x07, 0xb8, 0xfc, 0x72, 0xc4, 0x0d,
	0x6d, 0x26, 0x72, 0x1e, 0xaf, 0x21, 0xa9, 0xab, 0x54, 0x64, 0xa2, 0x38, 0x6b, 0x92, 0xba, 0xca,
	0xdf, 0xe1, 0x6a, 0xa1, 0xdd, 0x68, 0x8d, 0x23, 0x44, 0x38, 0x35, 0x6a, 0xa0, 0xa8, 0xb8, 0x68,
	0x22, 0xc6, 0x1b, 0x38, 0x51, 0x3d, 0xa5, 0x49, 0x3c, 0x9a, 0xe1, 0xeb, 0x56, 0x2c, 0xae, 0x2d,
	0x71, 0xd0, 0x1d, 0xe1, 0x37, 0xdc, 0x7d, 0x92, 0x9f, 0x37, 0xb5, 0xf9, 0xb3, 0x6d, 0x8c, 0x6f,
	0x3d, 0x93, 0x1a, 0xf0, 0x49, 0xee, 0x97, 0x92, 0xab, 0x46, 0xf7, 0xd9, 0x61, 0xc1, 0xd2, 0xa9,
	0x14, 0xd8, 0xc3, 0xe3, 0xca, 0xff, 0x43, 0xff, 0x6a, 0xa6, 0xce, 0x6b, 0x6b, 0xd4, 0xff, 0xd1,
	0x62, 0x0a, 0x51, 0x8a, 0x9f, 0xf3, 0xf8, 0xc8, 0xb7, 0x5d, 0x00, 0x00, 0x00, 0xff, 0xff, 0xd8,
	0xfc, 0xbb, 0xb3, 0x62, 0x01, 0x00, 0x00,
}
