// Code generated by protoc-gen-go. DO NOT EDIT.
// source: stringprocess.proto

package eci_v1_svr_stringprocess

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type OriginalStrReq struct {
	OriginalString       string   `protobuf:"bytes,1,opt,name=originalString,proto3" json:"originalString,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OriginalStrReq) Reset()         { *m = OriginalStrReq{} }
func (m *OriginalStrReq) String() string { return proto.CompactTextString(m) }
func (*OriginalStrReq) ProtoMessage()    {}
func (*OriginalStrReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0e9554c81f29977, []int{0}
}

func (m *OriginalStrReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OriginalStrReq.Unmarshal(m, b)
}
func (m *OriginalStrReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OriginalStrReq.Marshal(b, m, deterministic)
}
func (m *OriginalStrReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OriginalStrReq.Merge(m, src)
}
func (m *OriginalStrReq) XXX_Size() int {
	return xxx_messageInfo_OriginalStrReq.Size(m)
}
func (m *OriginalStrReq) XXX_DiscardUnknown() {
	xxx_messageInfo_OriginalStrReq.DiscardUnknown(m)
}

var xxx_messageInfo_OriginalStrReq proto.InternalMessageInfo

func (m *OriginalStrReq) GetOriginalString() string {
	if m != nil {
		return m.OriginalString
	}
	return ""
}

type UpperStrRes struct {
	UpperString          string   `protobuf:"bytes,1,opt,name=upperString,proto3" json:"upperString,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpperStrRes) Reset()         { *m = UpperStrRes{} }
func (m *UpperStrRes) String() string { return proto.CompactTextString(m) }
func (*UpperStrRes) ProtoMessage()    {}
func (*UpperStrRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0e9554c81f29977, []int{1}
}

func (m *UpperStrRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpperStrRes.Unmarshal(m, b)
}
func (m *UpperStrRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpperStrRes.Marshal(b, m, deterministic)
}
func (m *UpperStrRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpperStrRes.Merge(m, src)
}
func (m *UpperStrRes) XXX_Size() int {
	return xxx_messageInfo_UpperStrRes.Size(m)
}
func (m *UpperStrRes) XXX_DiscardUnknown() {
	xxx_messageInfo_UpperStrRes.DiscardUnknown(m)
}

var xxx_messageInfo_UpperStrRes proto.InternalMessageInfo

func (m *UpperStrRes) GetUpperString() string {
	if m != nil {
		return m.UpperString
	}
	return ""
}

func init() {
	proto.RegisterType((*OriginalStrReq)(nil), "eci.v1.svr.stringprocess.OriginalStrReq")
	proto.RegisterType((*UpperStrRes)(nil), "eci.v1.svr.stringprocess.UpperStrRes")
}

func init() { proto.RegisterFile("stringprocess.proto", fileDescriptor_a0e9554c81f29977) }

var fileDescriptor_a0e9554c81f29977 = []byte{
	// 159 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2e, 0x2e, 0x29, 0xca,
	0xcc, 0x4b, 0x2f, 0x28, 0xca, 0x4f, 0x4e, 0x2d, 0x2e, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17,
	0x92, 0x48, 0x4d, 0xce, 0xd4, 0x2b, 0x33, 0xd4, 0x2b, 0x2e, 0x2b, 0xd2, 0x43, 0x91, 0x57, 0xb2,
	0xe0, 0xe2, 0xf3, 0x2f, 0xca, 0x4c, 0xcf, 0xcc, 0x4b, 0xcc, 0x09, 0x2e, 0x29, 0x0a, 0x4a, 0x2d,
	0x14, 0x52, 0xe3, 0xe2, 0xcb, 0x47, 0x88, 0x64, 0xe6, 0xa5, 0x4b, 0x30, 0x2a, 0x30, 0x6a, 0x70,
	0x06, 0xa1, 0x89, 0x2a, 0xe9, 0x73, 0x71, 0x87, 0x16, 0x14, 0xa4, 0x16, 0x81, 0xb5, 0x15, 0x0b,
	0x29, 0x70, 0x71, 0x97, 0x42, 0xb9, 0x08, 0x3d, 0xc8, 0x42, 0x46, 0xb9, 0x5c, 0xbc, 0x10, 0x56,
	0x00, 0xc4, 0x6e, 0xa1, 0x18, 0x2e, 0xf6, 0x90, 0x7c, 0xb0, 0x19, 0x42, 0x1a, 0x7a, 0xb8, 0x5c,
	0xa8, 0x87, 0xea, 0x3c, 0x29, 0x55, 0xdc, 0x2a, 0x91, 0x9c, 0xa3, 0xc4, 0x90, 0xc4, 0x06, 0xf6,
	0xba, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x03, 0x80, 0xec, 0x9d, 0x11, 0x01, 0x00, 0x00,
}
