apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: nginx-injector-pod-control
  labels:
    app: nginx-injector
webhooks:
- name: nginx-injector-pod-webhook.calmwu.org
  failurePolicy: Fail # Fail定义了如何处理 admission webhook 中无法识别的错误和超时错误。允许的值为Ignore或Fail，
                      # Ignore表示调用 webhook 的错误将被忽略并且允许 API 请求继续。
                      # Fail表示调用 webhook 的错误导致准入失败并且 API 请求被拒绝。
  clientConfig:
    service:
      name: nginx-injector-pod-webhook-svc
      namespace: nginx-injector-pod-webhook
      path: "/inject"
      port: 8443
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUR2akNDQXFhZ0F3SUJBZ0lVUFQ4V3grUkV5TDBiNWc3Y0I5ZmVmRUVsSVdJd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1pURUxNQWtHQTFVRUJoTUNRMDR4RURBT0JnTlZCQWdUQjBKbGFVcHBibWN4RURBT0JnTlZCQWNUQjBKbAphVXBwYm1jeEREQUtCZ05WQkFvVEEyczRjekVQTUEwR0ExVUVDeE1HVTNsemRHVnRNUk13RVFZRFZRUURFd3ByCmRXSmxjbTVsZEdWek1CNFhEVEl4TURVeE1qQXpOVFF3TUZvWERUSTJNRFV4TVRBek5UUXdNRm93WlRFTE1Ba0cKQTFVRUJoTUNRMDR4RURBT0JnTlZCQWdUQjBKbGFVcHBibWN4RURBT0JnTlZCQWNUQjBKbGFVcHBibWN4RERBSwpCZ05WQkFvVEEyczRjekVQTUEwR0ExVUVDeE1HVTNsemRHVnRNUk13RVFZRFZRUURFd3ByZFdKbGNtNWxkR1Z6Ck1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBdVNBY3pydE5Jd3Nra1FKR3owRWYKM1NIZU9wanhlc0NldUU0dlBrRDdzbmw4a0hpRG95bUtSWHRqQlJhQ1VjWER2MWQxNTYwWW10QVcveUFBb0VxVQpEaTN1M09JS3A1UDhxR1VpdnFRdDkxWWNiWHZhczZzVDQxQ3pQbW1FeFh5SXdwZHRzbzJOekVDQnpPTnRRSUtUCkMyQ1Y1alg2UGFZckZjeUJsdTNpQkg4ZWI3ZUpXZ2dHNFdoOTkrWGlLQlZMdjl1Y3NCU1JGQVZtRk9QNk1ETTEKZm94bzhKN2hiN0lwK09UcU93aTRYekRJS29BUnByWVlkNlUwNHVPN1lneExJajdIQ2J0anB6L3Bad0Jadk1NMQpyeVZWNjl0bldSeU5IN1dubk8wcEZXeFpRYVEwSkFKdDhJdUZQbGxHWmRPbFRub0U2QzlleUpKU0tZbjMzZU44CkVRSURBUUFCbzJZd1pEQU9CZ05WSFE4QkFmOEVCQU1DQVFZd0VnWURWUjBUQVFIL0JBZ3dCZ0VCL3dJQkFqQWQKQmdOVkhRNEVGZ1FVZXBLeFJOanRpWVE1eVdOelMxdFpmQkpBYm5zd0h3WURWUjBqQkJnd0ZvQVVlcEt4Uk5qdAppWVE1eVdOelMxdFpmQkpBYm5zd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFIakdpd1FpTDdTVTNiWU0zTWFLClphZFphMWhMOFdUS0dNZDlVYVdxK1JRRkZhNWFhVncvclNnb2pVbWNpdzhOYXcyQjlXMVI4NE5DZWRQUGduQS8KMU1KYVlpb3JJeHNrWmh4eEtrM1hlNHFHK01pNUxKUGJhSkRSSDQ0cS91Y3VPcjFCaVl3eUlISW5PcXNkS1kwNApHaVRLQXkrM0JMeFhhT3JWc0dYUzNUTWNMWXZSRzRFRnZFODZXbkF2RnpRZmhGSXlza21JU0lhWEpqaU4yREVQCndUd2d6VXJGRUsvVk9CL1lzMVUvWExENldzMGxpbjZybXFHQmloektVdFlOakhIOVJuazZveHZETENHTitCdTEKc1JEWUNqNkZlb0krUlhsT3cveXJTUG9sY29LdCtSZGZpbkhoNXpETldBS0Y2TDNQOS9CMlo4cUJ6SlBOYzNLVwpIOGc9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  rules:
  - operations: ["CREATE", "UPDATE"]
    apiGroups: [""] # 列出了一个或多个要匹配的 API 组。"" 是核心 API 组。"*" 匹配所有 API 组。
    apiVersions: ["v1"] # 列出了一个或多个要匹配的 API 版本。"*" 匹配所有 API 版本。
    resources: ["pods"]
  admissionReviewVersions: ["v1", "v1beta1"] # 字段指定可接受的 AdmissionReview 对象版本：
  namespaceSelector:
    matchLabels:
      nginx-injection: "enabled" # 名字空间具有值为 "enabled" 的 "nginx-injection" 标签
  #objectSelector:
  #  matchLabels:
  #    nginx-injection: "true" # 它将匹配带有标签 nginx-injection:true 的pod