apiVersion: v1
kind: Service
metadata:
  name: {{ .ServiceName }}
  labels:
    app: {{ .ServiceName }}
spec:
  ports:
    - port: 8000
      nodePort: 30008
      targetPort: 8000
      protocol: TCP
      name: http
  type: NodePort
  selector:
    app: {{ .ServiceName }}

