// Code generated by protoc-gen-go. DO NOT EDIT.
// source: eci_namespace.proto

package eci_v1_namespace

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CallRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CallRequest) Reset()         { *m = CallRequest{} }
func (m *CallRequest) String() string { return proto.CompactTextString(m) }
func (*CallRequest) ProtoMessage()    {}
func (*CallRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2de34d336ef65e9b, []int{0}
}

func (m *CallRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CallRequest.Unmarshal(m, b)
}
func (m *CallRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CallRequest.Marshal(b, m, deterministic)
}
func (m *CallRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CallRequest.Merge(m, src)
}
func (m *CallRequest) XXX_Size() int {
	return xxx_messageInfo_CallRequest.Size(m)
}
func (m *CallRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CallRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CallRequest proto.InternalMessageInfo

func (m *CallRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type CallResponse struct {
	NamespaceInfo        string   `protobuf:"bytes,2,opt,name=namespaceInfo,proto3" json:"namespaceInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CallResponse) Reset()         { *m = CallResponse{} }
func (m *CallResponse) String() string { return proto.CompactTextString(m) }
func (*CallResponse) ProtoMessage()    {}
func (*CallResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2de34d336ef65e9b, []int{1}
}

func (m *CallResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CallResponse.Unmarshal(m, b)
}
func (m *CallResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CallResponse.Marshal(b, m, deterministic)
}
func (m *CallResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CallResponse.Merge(m, src)
}
func (m *CallResponse) XXX_Size() int {
	return xxx_messageInfo_CallResponse.Size(m)
}
func (m *CallResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CallResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CallResponse proto.InternalMessageInfo

func (m *CallResponse) GetNamespaceInfo() string {
	if m != nil {
		return m.NamespaceInfo
	}
	return ""
}

func init() {
	proto.RegisterType((*CallRequest)(nil), "eci.v1.namespace.CallRequest")
	proto.RegisterType((*CallResponse)(nil), "eci.v1.namespace.CallResponse")
}

func init() { proto.RegisterFile("eci_namespace.proto", fileDescriptor_2de34d336ef65e9b) }

var fileDescriptor_2de34d336ef65e9b = []byte{
	// 155 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4e, 0x4d, 0xce, 0x8c,
	0xcf, 0x4b, 0xcc, 0x4d, 0x2d, 0x2e, 0x48, 0x4c, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17,
	0x12, 0x48, 0x4d, 0xce, 0xd4, 0x2b, 0x33, 0xd4, 0x83, 0x8b, 0x2b, 0x29, 0x72, 0x71, 0x3b, 0x27,
	0xe6, 0xe4, 0x04, 0xa5, 0x16, 0x96, 0xa6, 0x16, 0x97, 0x08, 0x09, 0x71, 0xb1, 0x80, 0xe4, 0x24,
	0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0xc0, 0x6c, 0x25, 0x13, 0x2e, 0x1e, 0x88, 0x92, 0xe2, 0x82,
	0xfc, 0xbc, 0xe2, 0x54, 0x21, 0x15, 0x2e, 0x5e, 0xb8, 0x7e, 0xcf, 0xbc, 0xb4, 0x7c, 0x09, 0x26,
	0xb0, 0x62, 0x54, 0x41, 0xa3, 0x78, 0x2e, 0x1e, 0x3f, 0x98, 0x40, 0x70, 0x59, 0x91, 0x90, 0x3f,
	0x17, 0x8f, 0x7b, 0x6a, 0x09, 0x5c, 0x48, 0x48, 0x56, 0x0f, 0xdd, 0x2d, 0x7a, 0x48, 0x0e, 0x91,
	0x92, 0xc3, 0x25, 0x0d, 0x71, 0x84, 0x12, 0x43, 0x12, 0x1b, 0xd8, 0x4b, 0xc6, 0x80, 0x00, 0x00,
	0x00, 0xff, 0xff, 0xdb, 0x20, 0xb2, 0x15, 0xe9, 0x00, 0x00, 0x00,
}
