apiVersion: v1
kind: Pod
metadata:
  name: kata-nginxpod
  annotations:
    io.kubernetes.cri.untrusted-workload: "true"
  labels:
    name: kata-nginxpod
spec:
  containers:
  - name: kata-nginxpod
    image: nginx
    ports:
    - containerPort: 80
