apiVersion: v1
kind: Service #表明是kubernetes Service
metadata:
  name: kata-nginxsvc
spec:
  type: NodePort
  ports:
    - port: 8081
      targetPort: 80
      nodePort: 30081
  selector:
    name: kata-nginxpod