containers:
- name: sidecar-nginx
  image: nginx:1.16.1
  imagePullPolicy: IfNotPresent
  ports:
  - containerPort: 80
  volumeMounts:
  - name: nginx-conf
    mountPath: /etc/nginx
volumes:
- name: nginx-conf
  configMap:
    name: nginx-injector-pod-webhook-nginx-configmap