apiVersion: v1
kind: ReplicationController #副本控制器
metadata:
  name: mysql #rc的名称，全局唯一
spec:
  replicas: 1 #Pod副本期待数量
  selector: # 这是rc用来圈定选择pod的条件，这个必须匹配.spec.template.metadata.labels .spec.selector是可选字段，用来指定 label selector
    app: mysql
  template: # 这是个模板，如果直接是pod，这里就是明确的内容了
    metadata:
      labels:
        app: mysql #pod副本拥有的标签，service的select会通过这个来选择对应的pod
    spec:
      containers: #Pod内容器的定义部分
      - name: mysql #容器名称
        image: hub.c.163.com/library/mysql:5.5 #容器对应的Docker Image
        ports:
        - containerPort: 3306 #容器暴露的端口号
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "123456"
