apiVersion: v1
kind: ReplicationController #副本控制器
metadata:
  name: mysql #rc的名称，全局唯一
spec:
  replicas: 1 #Pod副本期待数量
  selector:
    app: mysql
  template:
    metadata:
      labels:
        app: mysql #pod副本拥有的标签，对应RC的Selector 这就是pod的标签
    spec:
      containers: #Pod内容器的定义部分
      - name: mysql #容器名称
        image: hub.c.163.com/library/mysql:5.5 #容器对应的Docker Image
        ports:
        - containerPort: 3306 #容器暴露的端口号
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "123456"
