// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sci_auth/sci_openapiauth.proto

package sci_v1_srv_opanapiauth

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
	sci_error "multi-call/api/protobuf/common/sci_error"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// AuthTokenReq
type AuthTokenReq struct {
	ReqID                string   `protobuf:"bytes,1,opt,name=reqID,proto3" json:"reqID,omitempty"`
	UserID               string   `protobuf:"bytes,2,opt,name=userID,proto3" json:"userID,omitempty"`
	UserPwd              string   `protobuf:"bytes,3,opt,name=userPwd,proto3" json:"userPwd,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthTokenReq) Reset()         { *m = AuthTokenReq{} }
func (m *AuthTokenReq) String() string { return proto.CompactTextString(m) }
func (*AuthTokenReq) ProtoMessage()    {}
func (*AuthTokenReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ede93ee946d3fd3, []int{0}
}

func (m *AuthTokenReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthTokenReq.Unmarshal(m, b)
}
func (m *AuthTokenReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthTokenReq.Marshal(b, m, deterministic)
}
func (m *AuthTokenReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthTokenReq.Merge(m, src)
}
func (m *AuthTokenReq) XXX_Size() int {
	return xxx_messageInfo_AuthTokenReq.Size(m)
}
func (m *AuthTokenReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthTokenReq.DiscardUnknown(m)
}

var xxx_messageInfo_AuthTokenReq proto.InternalMessageInfo

func (m *AuthTokenReq) GetReqID() string {
	if m != nil {
		return m.ReqID
	}
	return ""
}

func (m *AuthTokenReq) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *AuthTokenReq) GetUserPwd() string {
	if m != nil {
		return m.UserPwd
	}
	return ""
}

type AuthTokenRes struct {
	ReqID                string           `protobuf:"bytes,1,opt,name=reqID,proto3" json:"reqID,omitempty"`
	UserID               string           `protobuf:"bytes,2,opt,name=userID,proto3" json:"userID,omitempty"`
	Token                string           `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	Error                *sci_error.Error `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *AuthTokenRes) Reset()         { *m = AuthTokenRes{} }
func (m *AuthTokenRes) String() string { return proto.CompactTextString(m) }
func (*AuthTokenRes) ProtoMessage()    {}
func (*AuthTokenRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ede93ee946d3fd3, []int{1}
}

func (m *AuthTokenRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthTokenRes.Unmarshal(m, b)
}
func (m *AuthTokenRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthTokenRes.Marshal(b, m, deterministic)
}
func (m *AuthTokenRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthTokenRes.Merge(m, src)
}
func (m *AuthTokenRes) XXX_Size() int {
	return xxx_messageInfo_AuthTokenRes.Size(m)
}
func (m *AuthTokenRes) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthTokenRes.DiscardUnknown(m)
}

var xxx_messageInfo_AuthTokenRes proto.InternalMessageInfo

func (m *AuthTokenRes) GetReqID() string {
	if m != nil {
		return m.ReqID
	}
	return ""
}

func (m *AuthTokenRes) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *AuthTokenRes) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *AuthTokenRes) GetError() *sci_error.Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type VerifyTokenReq struct {
	ReqID                string   `protobuf:"bytes,1,opt,name=reqID,proto3" json:"reqID,omitempty"`
	JtwToken             string   `protobuf:"bytes,2,opt,name=jtwToken,proto3" json:"jtwToken,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyTokenReq) Reset()         { *m = VerifyTokenReq{} }
func (m *VerifyTokenReq) String() string { return proto.CompactTextString(m) }
func (*VerifyTokenReq) ProtoMessage()    {}
func (*VerifyTokenReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ede93ee946d3fd3, []int{2}
}

func (m *VerifyTokenReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyTokenReq.Unmarshal(m, b)
}
func (m *VerifyTokenReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyTokenReq.Marshal(b, m, deterministic)
}
func (m *VerifyTokenReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyTokenReq.Merge(m, src)
}
func (m *VerifyTokenReq) XXX_Size() int {
	return xxx_messageInfo_VerifyTokenReq.Size(m)
}
func (m *VerifyTokenReq) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyTokenReq.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyTokenReq proto.InternalMessageInfo

func (m *VerifyTokenReq) GetReqID() string {
	if m != nil {
		return m.ReqID
	}
	return ""
}

func (m *VerifyTokenReq) GetJtwToken() string {
	if m != nil {
		return m.JtwToken
	}
	return ""
}

type VerifyTokenRes struct {
	ReqID                string           `protobuf:"bytes,1,opt,name=reqID,proto3" json:"reqID,omitempty"`
	Error                *sci_error.Error `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *VerifyTokenRes) Reset()         { *m = VerifyTokenRes{} }
func (m *VerifyTokenRes) String() string { return proto.CompactTextString(m) }
func (*VerifyTokenRes) ProtoMessage()    {}
func (*VerifyTokenRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ede93ee946d3fd3, []int{3}
}

func (m *VerifyTokenRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyTokenRes.Unmarshal(m, b)
}
func (m *VerifyTokenRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyTokenRes.Marshal(b, m, deterministic)
}
func (m *VerifyTokenRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyTokenRes.Merge(m, src)
}
func (m *VerifyTokenRes) XXX_Size() int {
	return xxx_messageInfo_VerifyTokenRes.Size(m)
}
func (m *VerifyTokenRes) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyTokenRes.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyTokenRes proto.InternalMessageInfo

func (m *VerifyTokenRes) GetReqID() string {
	if m != nil {
		return m.ReqID
	}
	return ""
}

func (m *VerifyTokenRes) GetError() *sci_error.Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func init() {
	proto.RegisterType((*AuthTokenReq)(nil), "sci.v1.srv.opanapiauth.AuthTokenReq")
	proto.RegisterType((*AuthTokenRes)(nil), "sci.v1.srv.opanapiauth.AuthTokenRes")
	proto.RegisterType((*VerifyTokenReq)(nil), "sci.v1.srv.opanapiauth.VerifyTokenReq")
	proto.RegisterType((*VerifyTokenRes)(nil), "sci.v1.srv.opanapiauth.VerifyTokenRes")
}

func init() { proto.RegisterFile("sci_auth/sci_openapiauth.proto", fileDescriptor_6ede93ee946d3fd3) }

var fileDescriptor_6ede93ee946d3fd3 = []byte{
	// 331 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0x41, 0x4f, 0x32, 0x31,
	0x10, 0x65, 0xbf, 0x4f, 0x50, 0x07, 0xc3, 0xa1, 0x21, 0xb8, 0xd9, 0x44, 0x43, 0x36, 0xc6, 0x70,
	0xa1, 0x1b, 0xd1, 0x3f, 0xa0, 0xc1, 0x03, 0x27, 0x09, 0x2a, 0x47, 0x49, 0x59, 0x4b, 0xa8, 0xee,
	0xb6, 0xa5, 0xed, 0x42, 0xf4, 0xe6, 0x3f, 0xf5, 0xa7, 0x98, 0x76, 0x59, 0x03, 0x46, 0x22, 0x5c,
	0x9a, 0x79, 0x33, 0x6f, 0xde, 0xce, 0x9b, 0x59, 0x38, 0xd5, 0x31, 0x1b, 0x91, 0xcc, 0x4c, 0x23,
	0x1b, 0x08, 0x49, 0x39, 0x91, 0xcc, 0x62, 0x2c, 0x95, 0x30, 0x02, 0x35, 0x74, 0xcc, 0xf0, 0xfc,
	0x02, 0x6b, 0x35, 0xc7, 0x42, 0x92, 0xa2, 0x1a, 0x5c, 0xa5, 0x59, 0x62, 0x58, 0x3b, 0x26, 0x49,
	0x12, 0x11, 0xc9, 0x22, 0xc7, 0x1e, 0x67, 0x93, 0x28, 0x16, 0x69, 0x2a, 0xb8, 0x53, 0xa3, 0x4a,
	0x09, 0x15, 0xb9, 0x37, 0x57, 0x0b, 0x87, 0x70, 0x74, 0x9d, 0x99, 0xe9, 0x83, 0x78, 0xa5, 0x7c,
	0x40, 0x67, 0xa8, 0x0e, 0x65, 0x45, 0x67, 0xbd, 0xae, 0xef, 0x35, 0xbd, 0xd6, 0xe1, 0x20, 0x07,
	0xa8, 0x01, 0x95, 0x4c, 0x53, 0xd5, 0xeb, 0xfa, 0xff, 0x5c, 0x7a, 0x89, 0x90, 0x0f, 0xfb, 0x36,
	0xea, 0x2f, 0x9e, 0xfd, 0xff, 0xae, 0x50, 0xc0, 0xf0, 0xc3, 0x5b, 0x13, 0xd6, 0x3b, 0x0a, 0xd7,
	0xa1, 0x6c, 0x6c, 0xe7, 0x52, 0x36, 0x07, 0xa8, 0x0d, 0x65, 0x37, 0xbb, 0xbf, 0xd7, 0xf4, 0x5a,
	0xd5, 0xce, 0x31, 0x2e, 0x56, 0x51, 0x58, 0xc3, 0xb7, 0xf6, 0x1d, 0xe4, 0xac, 0xf0, 0x06, 0x6a,
	0x43, 0xaa, 0xd8, 0xe4, 0xed, 0x0f, 0x77, 0x01, 0x1c, 0xbc, 0x98, 0x85, 0x23, 0x2d, 0xc7, 0xf8,
	0xc6, 0xe1, 0xe3, 0x0f, 0x8d, 0x4d, 0x46, 0x76, 0x1b, 0xad, 0xf3, 0xe9, 0xc1, 0xc9, 0x9d, 0xa4,
	0xbc, 0x9f, 0x10, 0x33, 0x11, 0x2a, 0xb5, 0xab, 0xa2, 0xdc, 0xb0, 0x98, 0x18, 0x26, 0xf8, 0xbd,
	0x9a, 0xa3, 0x27, 0xa8, 0xd9, 0xa4, 0x50, 0xec, 0x9d, 0xba, 0x6f, 0xa3, 0x33, 0xfc, 0xfb, 0xe5,
	0xf1, 0xea, 0x01, 0x83, 0x6d, 0x58, 0x3a, 0x2c, 0xa1, 0x11, 0x54, 0x57, 0x8c, 0xa1, 0xf3, 0x4d,
	0x6d, 0xeb, 0x1b, 0x0c, 0xb6, 0xe3, 0xe9, 0xb0, 0x34, 0xae, 0xb8, 0x1f, 0xec, 0xf2, 0x2b, 0x00,
	0x00, 0xff, 0xff, 0x5f, 0x85, 0x6a, 0x1d, 0xd0, 0x02, 0x00, 0x00,
}
