// Code generated by protoc-gen-go. DO NOT EDIT.
// source: srv-split/strsplit.proto

package sci_v1_svr_strsplit

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	_struct "github.com/golang/protobuf/ptypes/struct"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type StrSplitReq struct {
	OriginalString       string   `protobuf:"bytes,1,opt,name=originalString,proto3" json:"originalString,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StrSplitReq) Reset()         { *m = StrSplitReq{} }
func (m *StrSplitReq) String() string { return proto.CompactTextString(m) }
func (*StrSplitReq) ProtoMessage()    {}
func (*StrSplitReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_4906702bab5ee7b7, []int{0}
}

func (m *StrSplitReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StrSplitReq.Unmarshal(m, b)
}
func (m *StrSplitReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StrSplitReq.Marshal(b, m, deterministic)
}
func (m *StrSplitReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StrSplitReq.Merge(m, src)
}
func (m *StrSplitReq) XXX_Size() int {
	return xxx_messageInfo_StrSplitReq.Size(m)
}
func (m *StrSplitReq) XXX_DiscardUnknown() {
	xxx_messageInfo_StrSplitReq.DiscardUnknown(m)
}

var xxx_messageInfo_StrSplitReq proto.InternalMessageInfo

func (m *StrSplitReq) GetOriginalString() string {
	if m != nil {
		return m.OriginalString
	}
	return ""
}

type StrSplitRes struct {
	SplitStrs            []string `protobuf:"bytes,1,rep,name=splitStrs,proto3" json:"splitStrs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StrSplitRes) Reset()         { *m = StrSplitRes{} }
func (m *StrSplitRes) String() string { return proto.CompactTextString(m) }
func (*StrSplitRes) ProtoMessage()    {}
func (*StrSplitRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_4906702bab5ee7b7, []int{1}
}

func (m *StrSplitRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StrSplitRes.Unmarshal(m, b)
}
func (m *StrSplitRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StrSplitRes.Marshal(b, m, deterministic)
}
func (m *StrSplitRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StrSplitRes.Merge(m, src)
}
func (m *StrSplitRes) XXX_Size() int {
	return xxx_messageInfo_StrSplitRes.Size(m)
}
func (m *StrSplitRes) XXX_DiscardUnknown() {
	xxx_messageInfo_StrSplitRes.DiscardUnknown(m)
}

var xxx_messageInfo_StrSplitRes proto.InternalMessageInfo

func (m *StrSplitRes) GetSplitStrs() []string {
	if m != nil {
		return m.SplitStrs
	}
	return nil
}

type HelloWorldRequest struct {
	Greeting             string          `protobuf:"bytes,1,opt,name=greeting,proto3" json:"greeting,omitempty"`
	Values               *_struct.Struct `protobuf:"bytes,2,opt,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *HelloWorldRequest) Reset()         { *m = HelloWorldRequest{} }
func (m *HelloWorldRequest) String() string { return proto.CompactTextString(m) }
func (*HelloWorldRequest) ProtoMessage()    {}
func (*HelloWorldRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4906702bab5ee7b7, []int{2}
}

func (m *HelloWorldRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloWorldRequest.Unmarshal(m, b)
}
func (m *HelloWorldRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloWorldRequest.Marshal(b, m, deterministic)
}
func (m *HelloWorldRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloWorldRequest.Merge(m, src)
}
func (m *HelloWorldRequest) XXX_Size() int {
	return xxx_messageInfo_HelloWorldRequest.Size(m)
}
func (m *HelloWorldRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloWorldRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HelloWorldRequest proto.InternalMessageInfo

func (m *HelloWorldRequest) GetGreeting() string {
	if m != nil {
		return m.Greeting
	}
	return ""
}

func (m *HelloWorldRequest) GetValues() *_struct.Struct {
	if m != nil {
		return m.Values
	}
	return nil
}

type HelloWorldResponse struct {
	Reply                string   `protobuf:"bytes,1,opt,name=reply,proto3" json:"reply,omitempty"`
	Detail               *any.Any `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloWorldResponse) Reset()         { *m = HelloWorldResponse{} }
func (m *HelloWorldResponse) String() string { return proto.CompactTextString(m) }
func (*HelloWorldResponse) ProtoMessage()    {}
func (*HelloWorldResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4906702bab5ee7b7, []int{3}
}

func (m *HelloWorldResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloWorldResponse.Unmarshal(m, b)
}
func (m *HelloWorldResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloWorldResponse.Marshal(b, m, deterministic)
}
func (m *HelloWorldResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloWorldResponse.Merge(m, src)
}
func (m *HelloWorldResponse) XXX_Size() int {
	return xxx_messageInfo_HelloWorldResponse.Size(m)
}
func (m *HelloWorldResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloWorldResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HelloWorldResponse proto.InternalMessageInfo

func (m *HelloWorldResponse) GetReply() string {
	if m != nil {
		return m.Reply
	}
	return ""
}

func (m *HelloWorldResponse) GetDetail() *any.Any {
	if m != nil {
		return m.Detail
	}
	return nil
}

func init() {
	proto.RegisterType((*StrSplitReq)(nil), "sci.v1.svr.strsplit.StrSplitReq")
	proto.RegisterType((*StrSplitRes)(nil), "sci.v1.svr.strsplit.StrSplitRes")
	proto.RegisterType((*HelloWorldRequest)(nil), "sci.v1.svr.strsplit.HelloWorldRequest")
	proto.RegisterType((*HelloWorldResponse)(nil), "sci.v1.svr.strsplit.HelloWorldResponse")
}

func init() { proto.RegisterFile("srv-split/strsplit.proto", fileDescriptor_4906702bab5ee7b7) }

var fileDescriptor_4906702bab5ee7b7 = []byte{
	// 317 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x91, 0xc1, 0x4a, 0xf3, 0x40,
	0x10, 0xc7, 0x9b, 0xef, 0xa3, 0xc5, 0x4e, 0x51, 0x71, 0x2d, 0x18, 0x43, 0x0f, 0x21, 0x87, 0x5a,
	0x50, 0x37, 0x58, 0xf1, 0x01, 0xbc, 0x79, 0x11, 0x24, 0x39, 0xe8, 0xd1, 0xb4, 0x1d, 0x43, 0x60,
	0xc9, 0xa6, 0x33, 0x9b, 0x40, 0xde, 0xcf, 0x07, 0x13, 0x37, 0xa9, 0x0d, 0x6d, 0xa1, 0xb7, 0x9d,
	0x99, 0xdf, 0xfc, 0x67, 0xfe, 0xb3, 0xe0, 0x32, 0x55, 0xf7, 0x5c, 0xa8, 0xcc, 0x84, 0x6c, 0xc8,
	0x3e, 0x64, 0x41, 0xda, 0x68, 0x71, 0xc9, 0xcb, 0x4c, 0x56, 0x0f, 0x92, 0x2b, 0x92, 0x9b, 0x92,
	0x77, 0x9d, 0x6a, 0x9d, 0x2a, 0x0c, 0x2d, 0xb2, 0x28, 0xbf, 0xc2, 0x24, 0xaf, 0x1b, 0xde, 0x9b,
	0xec, 0x96, 0xd8, 0x50, 0xb9, 0x6c, 0xd5, 0x82, 0x27, 0x18, 0xc5, 0x86, 0xe2, 0x5f, 0x91, 0x08,
	0xd7, 0x62, 0x0a, 0x67, 0x9a, 0xb2, 0x34, 0xcb, 0x13, 0x15, 0x1b, 0xca, 0xf2, 0xd4, 0x75, 0x7c,
	0x67, 0x36, 0x8c, 0x76, 0xb2, 0xc1, 0x6d, 0xb7, 0x8d, 0xc5, 0x04, 0x86, 0x76, 0x8f, 0xd8, 0x10,
	0xbb, 0x8e, 0xff, 0x7f, 0x36, 0x8c, 0xb6, 0x89, 0xe0, 0x13, 0x2e, 0x5e, 0x50, 0x29, 0xfd, 0xae,
	0x49, 0xad, 0x22, 0x5c, 0x97, 0xc8, 0x46, 0x78, 0x70, 0x92, 0x12, 0xa2, 0xd9, 0xce, 0xf8, 0x8b,
	0x45, 0x08, 0x83, 0x2a, 0x51, 0x25, 0xb2, 0xfb, 0xcf, 0x77, 0x66, 0xa3, 0xf9, 0x95, 0x6c, 0x3c,
	0xc8, 0x8d, 0x07, 0x19, 0x5b, 0x0f, 0x51, 0x8b, 0x05, 0x1f, 0x20, 0xba, 0x13, 0xb8, 0xd0, 0x39,
	0xa3, 0x18, 0x43, 0x9f, 0xb0, 0x50, 0x75, 0xab, 0xdf, 0x04, 0xe2, 0x0e, 0x06, 0x2b, 0x34, 0x49,
	0xa6, 0x5a, 0xf1, 0xf1, 0x9e, 0xf8, 0x73, 0x5e, 0x47, 0x2d, 0x33, 0xff, 0x76, 0xe0, 0x7c, 0xe3,
	0xf4, 0x8d, 0xf4, 0x12, 0x99, 0xc5, 0x2b, 0xf4, 0x6d, 0x2c, 0x7c, 0x79, 0xe0, 0x2f, 0x64, 0xe7,
	0x9e, 0xde, 0x31, 0x82, 0x83, 0x9e, 0x58, 0xc0, 0x69, 0x9c, 0xd4, 0xdb, 0xfd, 0xc5, 0xf4, 0x60,
	0xd3, 0xde, 0x09, 0xbd, 0x9b, 0xa3, 0x5c, 0x73, 0x88, 0xa0, 0xb7, 0x18, 0x58, 0x73, 0x8f, 0x3f,
	0x01, 0x00, 0x00, 0xff, 0xff, 0x52, 0xe6, 0x9b, 0xb3, 0x57, 0x02, 0x00, 0x00,
}
