apiVersion: apps/v1
kind: Deployment
metadata:
  name: elbservice-operator
spec:
  replicas: 2
  selector:
    matchLabels:
      name: elbservice-operator
  template:
    metadata:
      labels:
        name: elbservice-operator
    spec:
      serviceAccountName: elbservice-operator
      containers:
        - name: elbservice-operator
          # Replace this with the built image name
          image: REPLACE_IMAGE
          command:
          - elbservice-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "elbservice-operator"
