kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: elbservice-operator
subjects:
- kind: ServiceAccount
  name: elbservice-operator
  namespace: calmwu-namespace
roleRef:
  kind: ClusterRole
  name: elbservice-operator
  apiGroup: rbac.authorization.k8s.io
