apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  namespace: istio-ns
  name: simplehttp-destination
spec:
  host: simplehttp.istio-ns.svc.cluster.local
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN  
  subsets:
  - name: v1
    labels:
     version: v1
  - name: v2
    labels:
      version: v2
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  namespace: istio-ns
  name: simplehttp-route
spec:
  #客户端访问服务的地址，k8s service全名称
  hosts:
  - simplehttp.istio-ns.svc.cluster.local
  http:
  - route:
    - destination:
        host: simplehttp.istio-ns.svc.cluster.local
        subset: v1
      weight: 50
    - destination:
        host: simplehttp.istio-ns.svc.cluster.local
        subset: v2
      weight: 50     