# 定义文件，声明了一种名为Foo的资源，告诉API Server，有一种资源叫做Foo
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  # 名字由“复数名.分组名"构成，
  name: foos.samplecontroller.k8s.io
spec:
  # 分组名，在rest api中也会用到，格式是/apis/分组名/CRD版本，group/version会用到实例定义的的apiVersion中
  group: samplecontroller.k8s.io
  version: v1alpha1
  names:
    # 类型名
    kind: Foo
    # 复数名，可以kubectl describe crd foos查看
    plural: foos
    # 单数名，可以kubectl describe crd foo查看
    singular: foo
  # 范围是属于namespace的
  scope: Namespaced
