apiVersion: v1
kind: Service
metadata:
  name: calm-k8sapp
  labels:
    app: calm-k8sapp
spec:
  ports:
    - port: 8000
      nodePort: 8000
      targetPort: 8000
      protocol: TCP
      name: http
  type: NodePort
  selector:
    app: calm-k8sapp

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: calm-k8sapp
  labels:
    app: calm-k8sapp
spec:
  selector:
    matchLabels:
      app: calm-k8sapp 
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50%
      maxSurge: 1
  template:
    metadata:
      labels:
        app: calm-k8sapp
    spec:
      containers:
      - name: calm-k8sapp
        image: docker.io/library/calm-k8sapp:0.0.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8000
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8000
        resources:
          limits:
            cpu: 10m
            memory: 30Mi
          requests:
            cpu: 10m
            memory: 30Mi
      terminationGracePeriodSeconds: 30

---
