apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kata-ngsvr-ss
  annotations:
    io.kubernetes.cri.untrusted-workload: "true"  
spec:
  serviceName: kata-ngsvr-ss
  selector:
    matchLabels:
      app: kata-ngsvr-ss
  replicas: 2
  template:
    metadata:
      labels:
        app: kata-ngsvr-ss
      annotations:
        io.kubernetes.cri.untrusted-workload: "true"         
    spec:
      containers:
      - name: kata-ngsvr-ss
        image: nginx:1.16.0
        ports:
        - containerPort: 80
