apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kata-ngss
  annotations:
    io.kubernetes.cri.untrusted-workload: "true"  
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: kata-ngss
      annotations:
        io.kubernetes.cri.untrusted-workload: "true"         
    spec:
      containers:
      - name: kata-ngss
        image: nginx:1.16.0
        ports:
        - containerPort: 80
