// Code generated by protoc-gen-go. DO NOT EDIT.
// source: server-b/strupper.proto

package sci_v1_svr_strupper

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type StrUpperReq struct {
	OriginalString       string   `protobuf:"bytes,1,opt,name=originalString,proto3" json:"originalString,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StrUpperReq) Reset()         { *m = StrUpperReq{} }
func (m *StrUpperReq) String() string { return proto.CompactTextString(m) }
func (*StrUpperReq) ProtoMessage()    {}
func (*StrUpperReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_c459ae2a1bdd72bd, []int{0}
}

func (m *StrUpperReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StrUpperReq.Unmarshal(m, b)
}
func (m *StrUpperReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StrUpperReq.Marshal(b, m, deterministic)
}
func (m *StrUpperReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StrUpperReq.Merge(m, src)
}
func (m *StrUpperReq) XXX_Size() int {
	return xxx_messageInfo_StrUpperReq.Size(m)
}
func (m *StrUpperReq) XXX_DiscardUnknown() {
	xxx_messageInfo_StrUpperReq.DiscardUnknown(m)
}

var xxx_messageInfo_StrUpperReq proto.InternalMessageInfo

func (m *StrUpperReq) GetOriginalString() string {
	if m != nil {
		return m.OriginalString
	}
	return ""
}

type StrUpperRes struct {
	OriginalString       string   `protobuf:"bytes,1,opt,name=originalString,proto3" json:"originalString,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StrUpperRes) Reset()         { *m = StrUpperRes{} }
func (m *StrUpperRes) String() string { return proto.CompactTextString(m) }
func (*StrUpperRes) ProtoMessage()    {}
func (*StrUpperRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_c459ae2a1bdd72bd, []int{1}
}

func (m *StrUpperRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StrUpperRes.Unmarshal(m, b)
}
func (m *StrUpperRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StrUpperRes.Marshal(b, m, deterministic)
}
func (m *StrUpperRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StrUpperRes.Merge(m, src)
}
func (m *StrUpperRes) XXX_Size() int {
	return xxx_messageInfo_StrUpperRes.Size(m)
}
func (m *StrUpperRes) XXX_DiscardUnknown() {
	xxx_messageInfo_StrUpperRes.DiscardUnknown(m)
}

var xxx_messageInfo_StrUpperRes proto.InternalMessageInfo

func (m *StrUpperRes) GetOriginalString() string {
	if m != nil {
		return m.OriginalString
	}
	return ""
}

func init() {
	proto.RegisterType((*StrUpperReq)(nil), "sci.v1.svr.strupper.StrUpperReq")
	proto.RegisterType((*StrUpperRes)(nil), "sci.v1.svr.strupper.StrUpperRes")
}

func init() { proto.RegisterFile("server-b/strupper.proto", fileDescriptor_c459ae2a1bdd72bd) }

var fileDescriptor_c459ae2a1bdd72bd = []byte{
	// 150 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2f, 0x4e, 0x2d, 0x2a,
	0x4b, 0x2d, 0xd2, 0x4d, 0xd2, 0x2f, 0x2e, 0x29, 0x2a, 0x2d, 0x28, 0x48, 0x2d, 0xd2, 0x2b, 0x28,
	0xca, 0x2f, 0xc9, 0x17, 0x12, 0x2e, 0x4e, 0xce, 0xd4, 0x2b, 0x33, 0xd4, 0x2b, 0x2e, 0x2b, 0xd2,
	0x83, 0x49, 0x29, 0x99, 0x72, 0x71, 0x07, 0x97, 0x14, 0x85, 0x82, 0xd8, 0x41, 0xa9, 0x85, 0x42,
	0x6a, 0x5c, 0x7c, 0xf9, 0x45, 0x99, 0xe9, 0x99, 0x79, 0x89, 0x39, 0xc1, 0x25, 0x45, 0x99, 0x79,
	0xe9, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x68, 0xa2, 0xa8, 0xda, 0x8a, 0x89, 0xd5, 0x66,
	0x94, 0xc4, 0xc5, 0x0f, 0xd3, 0x16, 0x50, 0x94, 0x9f, 0x9c, 0x5a, 0x5c, 0x2c, 0xe4, 0xcf, 0xc5,
	0x1e, 0x92, 0x0f, 0x16, 0x11, 0x52, 0xd0, 0xc3, 0xe2, 0x42, 0x3d, 0x24, 0xe7, 0x49, 0x11, 0x52,
	0x51, 0xac, 0xc4, 0x90, 0xc4, 0x06, 0xf6, 0xad, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x39, 0x67,
	0xe3, 0xe3, 0x08, 0x01, 0x00, 0x00,
}
