// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: server-b/strupper.proto

package sci_v1_svr_strupper

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for StrUpperProcess service

type StrUpperProcessService interface {
	ToUpper(ctx context.Context, in *StrUpperReq, opts ...client.CallOption) (*StrUpperRes, error)
}

type strUpperProcessService struct {
	c    client.Client
	name string
}

func NewStrUpperProcessService(name string, c client.Client) StrUpperProcessService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "sci.v1.svr.strupper"
	}
	return &strUpperProcessService{
		c:    c,
		name: name,
	}
}

func (c *strUpperProcessService) ToUpper(ctx context.Context, in *StrUpperReq, opts ...client.CallOption) (*StrUpperRes, error) {
	req := c.c.NewRequest(c.name, "StrUpperProcess.ToUpper", in)
	out := new(StrUpperRes)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for StrUpperProcess service

type StrUpperProcessHandler interface {
	ToUpper(context.Context, *StrUpperReq, *StrUpperRes) error
}

func RegisterStrUpperProcessHandler(s server.Server, hdlr StrUpperProcessHandler, opts ...server.HandlerOption) error {
	type strUpperProcess interface {
		ToUpper(ctx context.Context, in *StrUpperReq, out *StrUpperRes) error
	}
	type StrUpperProcess struct {
		strUpperProcess
	}
	h := &strUpperProcessHandler{hdlr}
	return s.Handle(s.NewHandler(&StrUpperProcess{h}, opts...))
}

type strUpperProcessHandler struct {
	StrUpperProcessHandler
}

func (h *strUpperProcessHandler) ToUpper(ctx context.Context, in *StrUpperReq, out *StrUpperRes) error {
	return h.StrUpperProcessHandler.ToUpper(ctx, in, out)
}
