// Code generated by "stringer -type=IPResMgrErrorCode"; DO NOT EDIT.

package protojson

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[IPResMgrErrnoSuccessed-0]
	_ = x[IPResMgrErrnoCreateIPPoolFailed-1]
	_ = x[IPResMgrErrnoReleaseIPPoolFailed-2]
	_ = x[IPResMgrErrnoScaleIPPoolFailed-3]
	_ = x[IPResMgrErrnoGetIPFailed-4]
	_ = x[IPResMgrErrnoReleaseIPFailed-5]
	_ = x[IPResMgrErrnoMaintainForceUnbindIPFailed-6]
	_ = x[IPResMgrErrnoMaintainForceReleaseK8SResourceIPPoolFailed-7]
	_ = x[IPResMgrErrnoMaintainForceReleasePodIPFailed-8]
}

const _IPResMgrErrorCode_name = "IPResMgrErrnoSuccessedIPResMgrErrnoCreateIPPoolFailedIPResMgrErrnoReleaseIPPoolFailedIPResMgrErrnoScaleIPPoolFailedIPResMgrErrnoGetIPFailedIPResMgrErrnoReleaseIPFailedIPResMgrErrnoMaintainForceUnbindIPFailedIPResMgrErrnoMaintainForceReleaseK8SResourceIPPoolFailedIPResMgrErrnoMaintainForceReleasePodIPFailed"

var _IPResMgrErrorCode_index = [...]uint16{0, 22, 53, 85, 115, 139, 167, 207, 263, 307}

func (i IPResMgrErrorCode) String() string {
	if i < 0 || i >= IPResMgrErrorCode(len(_IPResMgrErrorCode_index)-1) {
		return "IPResMgrErrorCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _IPResMgrErrorCode_name[_IPResMgrErrorCode_index[i]:_IPResMgrErrorCode_index[i+1]]
}
