// Code generated by "stringer -type K8SApiResourceKindType"; DO NOT EDIT.

package protojson

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[K8SApiResourceKindDeployment-0]
	_ = x[K8SApiResourceKindStatefulSet-1]
	_ = x[K8SApiResourceKindJob-2]
	_ = x[K8SApiResourceKindCronJob-3]
	_ = x[K8SApiResourceKindLikeJob-4]
}

const _K8SApiResourceKindType_name = "K8SApiResourceKindDeploymentK8SApiResourceKindStatefulSetK8SApiResourceKindJobK8SApiResourceKindCronJobK8SApiResourceKindLikeJob"

var _K8SApiResourceKindType_index = [...]uint8{0, 28, 57, 78, 103, 128}

func (i K8SApiResourceKindType) String() string {
	if i < 0 || i >= K8SApiResourceKindType(len(_K8SApiResourceKindType_index)-1) {
		return "K8SApiResourceKindType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _K8SApiResourceKindType_name[_K8SApiResourceKindType_index[i]:_K8SApiResourceKindType_index[i+1]]
}
