// Code generated by "stringer -type Maintain2IPResMgrRequestType"; DO NOT EDIT.

package protojson

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Maintain2IPResMgrDefaultReqType-0]
	_ = x[Maintain2IPResMgrForceUnbindIPReqType-1]
	_ = x[Maintain2IPResMgrForceReleaseK8SResourceIPPoolReqType-2]
	_ = x[Maintain2IPResMgrForceReleaseK8SPodIPReqType-3]
}

const _Maintain2IPResMgrRequestType_name = "Maintain2IPResMgrDefaultReqTypeMaintain2IPResMgrForceUnbindIPReqTypeMaintain2IPResMgrForceReleaseK8SResourceIPPoolReqTypeMaintain2IPResMgrForceReleaseK8SPodIPReqType"

var _Maintain2IPResMgrRequestType_index = [...]uint8{0, 31, 68, 121, 165}

func (i Maintain2IPResMgrRequestType) String() string {
	if i < 0 || i >= Maintain2IPResMgrRequestType(len(_Maintain2IPResMgrRequestType_index)-1) {
		return "Maintain2IPResMgrRequestType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Maintain2IPResMgrRequestType_name[_Maintain2IPResMgrRequestType_index[i]:_Maintain2IPResMgrRequestType_index[i+1]]
}
