// Code generated by "stringer -type WB2IPResMgrRequestType"; DO NOT EDIT.

package protojson

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[WB2IPResMgrRequestCreateIPPool-0]
	_ = x[WB2IPResMgrRequestReleaseIPPool-1]
	_ = x[WB2IPResMgrRequestScaleIPPool-2]
}

const _WB2IPResMgrRequestType_name = "WB2IPResMgrRequestCreateIPPoolWB2IPResMgrRequestReleaseIPPoolWB2IPResMgrRequestScaleIPPool"

var _WB2IPResMgrRequestType_index = [...]uint8{0, 30, 61, 90}

func (i WB2IPResMgrRequestType) String() string {
	if i < 0 || i >= WB2IPResMgrRequestType(len(_WB2IPResMgrRequestType_index)-1) {
		return "WB2IPResMgrRequestType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _WB2IPResMgrRequestType_name[_WB2IPResMgrRequestType_index[i]:_WB2IPResMgrRequestType_index[i+1]]
}
