apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: elbservices.k8s.calmwu.org
spec:
  group: k8s.calmwu.org
  names:
    kind: ELBService
    listKind: ELBServiceList
    plural: elbservices
    singular: elbservice
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: ELBService is the Schema for the elbservices API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: ELBServiceSpec defines the desired state of ELBService
          properties:
            elbinstance:
              description: 'INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
                Important: Run "operator-sdk generate k8s" to regenerate code after
                modifying this file Add custom validation using kubebuilder tags:
                https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html'
              properties:
                accesstype:
                  type: string
                autorenew:
                  type: boolean
                displayname:
                  type: string
                elbinstanceid:
                  type: string
                loadbalancetypeid:
                  type: string
                loadtype:
                  type: string
                networkid:
                  type: string
                regionid:
                  type: string
                subnetid:
                  type: string
                vip:
                  type: string
                vpcid:
                  type: string
                zoneid:
                  type: string
              required:
              - accesstype
              - autorenew
              - displayname
              - elbinstanceid
              - loadbalancetypeid
              - loadtype
              - networkid
              - regionid
              - subnetid
              - vip
              - vpcid
              - zoneid
              type: object
            elblisteners:
              items:
                description: ELBListener 监听器的参数
                properties:
                  containerport:
                    format: int32
                    type: integer
                  displayname:
                    type: string
                  frontport:
                    format: int32
                    type: integer
                  lbstrategy:
                    type: string
                  listenerid:
                    type: string
                  poolid:
                    type: string
                  protocol:
                    type: string
                required:
                - containerport
                - displayname
                - frontport
                - lbstrategy
                - listenerid
                - poolid
                - protocol
                type: object
              type: array
            selector:
              additionalProperties:
                type: string
              type: object
          required:
          - elbinstance
          - elblisteners
          type: object
        status:
          description: ELBServiceStatus defines the observed state of ELBService
          properties:
            lastUpdateTime:
              format: date-time
              type: string
            phase:
              description: 'INSERT ADDITIONAL STATUS FIELD - define observed state
                of cluster Important: Run "operator-sdk generate k8s" to regenerate
                code after modifying this file Add custom validation using kubebuilder
                tags: https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html'
              type: string
            podcount:
              format: int32
              type: integer
            podinfos:
              items:
                description: ELBPodInfo pod信息
                properties:
                  name:
                    type: string
                  podip:
                    type: string
                  status:
                    description: PodPhase is a label for the condition of a pod at
                      the current time.
                    type: string
                required:
                - name
                - podip
                - status
                type: object
              type: array
            reason:
              type: string
          required:
          - lastUpdateTime
          - phase
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
