apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: elbservices.k8s.calmwu.org
spec:
  group: k8s.calmwu.org
  names:
    kind: ELBService
    listKind: ELBServiceList
    plural: elbservices
    singular: elbservice
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: ELBService is the Schema for the elbservices API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: ELBServiceSpec defines the desired state of ELBService
          properties:
            elblistener:
              description: 'INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
                Important: Run "operator-sdk generate k8s" to regenerate code after
                modifying this file Add custom validation using kubebuilder tags:
                https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html'
              properties:
                lbstrategy:
                  description: LoadBalancingStrategy 负载均衡策略
                  type: string
                name:
                  type: string
                port:
                  format: int32
                  type: integer
                protocol:
                  type: string
                vip:
                  type: string
              required:
              - lbstrategy
              - name
              - port
              - protocol
              - vip
              type: object
            selector:
              additionalProperties:
                type: string
              type: object
          required:
          - elblistener
          type: object
        status:
          description: ELBServiceStatus defines the observed state of ELBService
          properties:
            lastUpdateTime:
              format: date-time
              type: string
            phase:
              description: 'INSERT ADDITIONAL STATUS FIELD - define observed state
                of cluster Important: Run "operator-sdk generate k8s" to regenerate
                code after modifying this file Add custom validation using kubebuilder
                tags: https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html'
              type: string
            podcount:
              format: int32
              type: integer
            podinfos:
              items:
                description: ELBPodInfo pod信息
                properties:
                  name:
                    type: string
                  podip:
                    type: string
                  status:
                    description: PodPhase is a label for the condition of a pod at
                      the current time.
                    type: string
                required:
                - name
                - podip
                - status
                type: object
              type: array
            reason:
              type: string
          required:
          - lastUpdateTime
          - phase
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
