apiVersion: v1
kind: Pod
metadata:
  namespace: istio-ns
  name: busybox-pod
  annotations:
    io.kubernetes.cri.untrusted-workload: "true" 
spec:
  containers:
  - name: busybox
    image: busybox:1.28.4
    imagePullPolicy: IfNotPresent
    command: ["sh", "-c", "sleep 3600"]