apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kata-ngdp
  annotations:
    io.kubernetes.cri.untrusted-workload: "true"  
spec:
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 1         #
      maxUnavailable: 0   #
    type: RollingUpdate   #  
  selector:
    matchLabels:
      app: kata-ngdp
  template:
    metadata:
      labels:
        app: kata-ngdp
      annotations:
        io.kubernetes.cri.untrusted-workload: "true"  
        # "Error adding network: cannot have more than one IPv4 address for "cni.projectcalico.org/ipAddrs" annotation"
        "cni.projectcalico.org/ipv4pools": "[\"calm.ippool-1\"]"
    spec:
      containers:
      - name: kata-ngdp
        image: nginx
        ports:
        - containerPort: 80