apiVersion: projectcalico.org/v3
kind: IPPool
metadata:
  name: calm.ippool-1
spec:
  blockSize: 31
  cidr: 10.245.55.200/31
  ipipMode: CrossSubnet
  natOutgoing: true
  disabled: false
  nodeSelector: all()