apiVersion: projectcalico.org/v3
kind: IPPool
metadata:
  name: calm.ippool-1
spec:
  blockSize: 30
  cidr: 10.245.55.200/30
  ipipMode: CrossSubnet
  natOutgoing: true
  disabled: false
  nodeSelector: all()