# permissions to do viewer students.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: student-viewer-role
rules:
- apiGroups:
  - studentcontroller.calmwu.org
  resources:
  - students
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - studentcontroller.calmwu.org
  resources:
  - students/status
  verbs:
  - get
