# permissions to do edit students.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: student-editor-role
rules:
- apiGroups:
  - studentcontroller.calmwu.org
  resources:
  - students
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - studentcontroller.calmwu.org
  resources:
  - students/status
  verbs:
  - get
  - patch
  - update
